Draft: Gene generator creation
unhindered-ec/unhindered-ec pull request #102
Opened 2024-03-03 14:43 UTC by JustusFluegel

This is meant to implement the `.into_gene_generator(CloseProbability::Uniform)` and `.to_gene_generator(CloseProbability::Given(0.1))` methods, but is currently waiting on https://github.com/rust-random/rand/pull/1402

2024-03-06 11:59 UTC, JustusFluegel commented
Ok this is mostly done, now only waiting on rand to release a new version with the `num_choices()` method included

@NicMcPhee you can review this if you feel inclined to, even if it is still a draft (the only changes would be removing the [patch] from Cargo.toml)

2024-03-06 21:07 UTC, JustusFluegel commented
Probably also a good idea to change the `.into../.to...` names at some point cuz they are quite long (maybe ask on stream for any better ideas?) but we can always do that in #48 if we want to

2024-03-07 13:09 UTC, JustusFluegel commented
The pr is now merged into main in rand, so it's a question of time till it's in the release

2024-03-22 08:33 UTC, JustusFluegel commented
Ok rand released `0.9.0-alpha.1` which contains my pr, so we should be good to go ahead and merge this. I think since this is not released anywhere it being an alpha version shouldn't really matter, and I don't think any major api changes will be introduced till the 0.9 release.

2024-04-21 16:21 UTC, NicMcPhee requested changes
This looks good but we should add tests for the new choices distribution constructor.

2024-04-21 16:21 UTC, NicMcPhee commented on packages/ec-core/src/distributions/wrappers/owned.rs
> +    num_choices: NonZeroUsize,
The relationship between these three fields needs to be clearly documented, and we should make sure we have tests (possibly doctests) that confirm that after calling `::new()` the relationships between these fields are preserved.

2024-04-21 16:58 UTC, NicMcPhee approved these changes

2024-04-21 17:10 UTC, merged