Fix clippy::redundant_type_annotations lint, enable it
unhindered-ec/unhindered-ec pull request #175
Opened 2024-05-11 14:30 UTC by JustusFluegel

Closes #161

2024-05-12 00:30 UTC, NicMcPhee submitted a review, later dismissed
I'm frankly amazed that these are the only two places that you needed to change to make this happy here!

2024-05-12 01:52 UTC, JustusFluegel commented
> I'm frankly amazed that these are the only two places that you needed to change to make this happy here!

I think this lint only checks pretty basic cases :)

2024-05-13 00:05 UTC, NicMcPhee requested changes

2024-05-13 00:05 UTC, NicMcPhee commented on Cargo.toml
> +
```suggestion

```

We don't want this blank line, do we?

2024-05-13 09:18 UTC, JustusFluegel commented
Same here

2024-05-13 15:41 UTC, NicMcPhee submitted a review, later dismissed

2024-05-13 16:59 UTC, merged