Fix the clippy::uneeded_field_pattern lint, enable it
unhindered-ec/unhindered-ec pull request #176
Opened 2024-05-11 14:37 UTC by JustusFluegel

Closes #166

2024-05-12 00:29 UTC, NicMcPhee approved these changes
Nice – thanks!

I need to be more aware of `..` than I am, so it's nice that both you and Clippy are here to keep me honest. 😜

2024-05-13 00:03 UTC, NicMcPhee requested changes

2024-05-13 00:03 UTC, NicMcPhee commented on Cargo.toml
> +
```suggestion



```

We don't need this white space, do we?

2024-05-13 00:03 UTC, NicMcPhee commented on Cargo.toml
> +
```suggestion





```

And again.

2024-05-13 08:53 UTC, JustusFluegel commented
And again. Sorry about that.

2024-05-13 15:41 UTC, NicMcPhee approved these changes

2024-05-13 15:44 UTC, merged