Use checked neg for integer negation (issue #191)
unhindered-ec/unhindered-ec pull request #199
Opened 2024-05-20 23:27 UTC by NicMcPhee

There's an edge case for the `Negate` instruction when the value is `i64::MIN` since negating that generates a wrapping error. This is because the two's complement representation used for integer types has an asymmetry where the magnitude of `MIN` is one larger than the magnitude of `MAX`. See <https://en.wikipedia.org/wiki/Two%27s_complement#Most_negative_number> for additional details and examples.

My solution here is to have `Negate` return `i64::MAX` when it negates `i64::MIN`. This isn't mathematically accurate, but is logically plausible since it converts the smallest negative number into the largest positive number.

The alternative would be to have this instruction "fail" in some way in this case, presumably by either being skipped or
generating a fatal error and terminating program evaluation. Neither of these options seem terribly reasonable from an evolutionary standpoint. 
- Skipping would leave the value on the stack, not negated, which would
be quite "surprising" and almost certainly leading to unexpected behavior.
- Failing doesn't seem to be in the spirit of Push, where we try to make
sure almost every instruction "succeeds" in some reasonable way.

So I went saturation. I'm open to alternatives, though.

Closes: #191

2024-05-20 23:30 UTC, NicMcPhee commented on packages/push/src/instruction/int/negate.rs
> +    fn negate(#[any] x: i64) {
I need to fix this `proptest` for `Negate` so that it won't fail if the value generated by `any` is `i64::MIN`.

2024-05-21 03:19 UTC, NicMcPhee commented on packages/push/src/instruction/int/negate.rs
> +    fn negate(#[any] x: i64) {
This is now dealt with in the following commit.

2024-05-21 13:51 UTC, NicMcPhee commented
I just realized that I should add a `# Differences` section to the documentation before we merge this.

2024-05-21 14:23 UTC, NicMcPhee commented
After some contemplation and a conversation with Google Gemini, I went with an orange badge saying "Saturates on overflow":

<img width="488" alt="image" src="https://github.com/unhindered-ec/unhindered-ec/assets/302297/da685d9a-3b49-488f-86a8-e4193dc65211">

I'm totally open to alternative suggestions for color and/or wording, however.

I also used Shields.io for this, although we could just use a little CSS in our Rustdocs and avoid the dependency on an outside service. Thoughts on that?

2024-05-21 17:01 UTC, NicMcPhee commented
One thing I noticed is that putting the Markdown to include the badge at the top of the documentation for `Negate` means that the alt-text for that image ends up being the "short form" documentation for `Negate` on the `push::instruction::int::negate` page:

<img width="490" alt="image" src="https://github.com/unhindered-ec/unhindered-ec/assets/302297/1904473c-c361-412f-98d9-96b6d606f3a6">

This doesn't seem awesome, but I'm not sure how to best address it. I don't want to move the badge lower on the page and I don't want to change the alt-text to be a more general description. Ideas?

2024-05-22 21:00 UTC, JustusFluegel requested changes
So generally this looks very reasonable to me :) But the thing with the docs & badges seems a bit unfortunate, and I'd say we should do something about it before merging this in. I don't think it's a huge issue for this to be open a few days longer, since the edgecase is currently so rare.

2024-06-22 17:01 UTC, JustusFluegel approved these changes

2024-06-22 17:07 UTC, merged